### PR TITLE
set SourceText internal slots

### PR DESCRIPTION
**Pull request by michaelficarra**
**DO NOT MERGE** until https://github.com/tc39/Function-prototype-toString-revision reaches stage 3.

### CODE REVIEW

**Comment by michaelficarra** [comment]
By the way, let me know what you want to do about the numbering.

**Comment by ljharb** [comment]
The `Function#toString` proposal is now stage 3! Can this be merged?

**Comment by michaelficarra** [comment]
Other than the list numbering inconsistency thing (which should be a separate issue), yes.

**Comment by bterlson** [comment]
I'll fix the numbering when I do the PR for 262.

**Pull request merged**
